package com.tradingdemo.service;

import com.tradingdemo.dao.AlertDAO;
import com.tradingdemo.model.AlertRule;
import com.tradingdemo.util.NotificationUtil;
import com.tradingdemo.notification.Notifier;
import com.tradingdemo.dao.UserDAO;
import com.tradingdemo.model.User;

import java.util.List;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

public class AlertService {
    private final AlertDAO alertDAO = new AlertDAO();
    private final ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
    private final PriceProvider priceProvider = new PriceProvider();
    private final Notifier emailNotifier;

    private static AlertService instance;

    private AlertService() {
        this.emailNotifier = com.tradingdemo.notification.NotifierFactory.getNotifier();
    }

    public static synchronized AlertService getInstance() {
        if (instance == null) instance = new AlertService();
        return instance;
    }

    public void start() {
        scheduler.scheduleAtFixedRate(this::checkAlerts, 5, 15, TimeUnit.SECONDS);
    }

    public void stop() { scheduler.shutdownNow(); }

    private void checkAlerts() {
        try {
            List<AlertRule> active = alertDAO.getActiveAlerts();
            for (AlertRule a : active) {
                double price = priceProvider.getPrice(a.getSymbol());
                boolean triggered = a.isNotifyWhenAbove() ? price >= a.getTargetPrice() : price <= a.getTargetPrice();
                if (triggered) {
                    String title = "Price Alert: " + a.getSymbol();
                    String msg = String.format("%s reached %.4f (target %.4f)", a.getSymbol(), price, a.getTargetPrice());
                    NotificationUtil.showPopup(title, msg);

                    // send email if requested and notifier configured
                    if (a.isNotifyEmail() && emailNotifier != null) {
                        try {
                            UserDAO userDAO = new UserDAO();
                            User u = userDAO.getUserById(a.getUserId());
                            if (u != null && u.getEmail() != null && !u.getEmail().isEmpty()) {
                                String subject = "Price Alert: " + a.getSymbol();
                                String body = msg + "\n\nThis alert was generated by Trading_wolfers.";
                                emailNotifier.sendEmail(u.getEmail(), subject, body);
                                System.out.println("Email alert sent to " + u.getEmail());
                            } else {
                                System.err.println("No email configured for user " + a.getUserId());
                            }
                        } catch (Exception ex) {
                            System.err.println("Failed to send email alert: " + ex.getMessage());
                        }
                    }

                    System.out.println("ALERT TRIGGERED: " + msg);
                    // Optionally disable alert after trigger
                    // a.setEnabled(false); alertDAO.updateAlert(a);
                }
            }
        } catch (Exception e) {
            System.err.println("Error checking alerts: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // Simple provider for demo - can be replaced with live API
    private static class PriceProvider {
        public double getPrice(String symbol) {
            switch (symbol.toUpperCase()) {
                case "BTC": return 69034.61;
                case "ETH": return 3542.88;
                case "BNB": return 421.35;
                case "ADA": return 0.58;
                case "SOL": return 125.43;
                default: return 1.0;
            }
        }
    }
}
